using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Vanadreams.Services
{
    public enum LoadKind { Plugin, Addon, PolPlugin, None }

    /// <summary>What one enabled catalogue item contributes to the startup script.</summary>
    public sealed class ScriptEntry
    {
        public string Id { get; set; }
        public LoadKind Kind { get; set; }
        public string LoadName { get; set; }
        public IList<string> ConfigLines { get; set; } = new List<string>();
    }

    /// <summary>
    /// Writes scripts\vanadreams.txt from the ticked items. Everything under the "yours"
    /// marker is the player's and is copied through untouched on every save.
    /// </summary>
    public static class ScriptWriter
    {
        public const string YoursMarker = "# --- yours ---";
        private const string YoursNote = "# Anything below this line is kept exactly as you wrote it.";

        public static string Build(IEnumerable<ScriptEntry> entries, string existingText)
        {
            var list = entries.ToList();
            var sb = new StringBuilder();
            sb.AppendLine("# Vanadreams startup script. Generated by the launcher from your Addons page.");
            sb.AppendLine("# Edit the Addons page to change what loads; write your own lines under the marker at the end.");
            sb.AppendLine();
            foreach (var e in list.Where(e => e.Kind == LoadKind.Plugin))
                sb.AppendLine("/load " + e.LoadName);
            sb.AppendLine("/load addons");
            foreach (var e in list.Where(e => e.Kind == LoadKind.Addon))
                sb.AppendLine("/addon load " + e.LoadName);
            sb.AppendLine();
            sb.AppendLine("# The wait is required: without it, addons do not see the commands below.");
            sb.AppendLine("/wait 3");
            sb.AppendLine();
            foreach (var e in list)
                foreach (var line in e.ConfigLines.Where(l => !string.IsNullOrWhiteSpace(l)))
                    sb.AppendLine(line.Trim());
            sb.AppendLine();
            sb.AppendLine(YoursMarker);
            sb.AppendLine(YoursNote);
            var yours = ExtractYours(existingText);
            if (yours.Length > 0) sb.Append(yours);
            return sb.ToString();
        }

        /// <summary>The player's block from a previous script, without the marker lines; empty when there is none.</summary>
        public static string ExtractYours(string existingText)
        {
            if (string.IsNullOrEmpty(existingText)) return "";
            var lines = existingText.Replace("\r\n", "\n").Split('\n').ToList();
            var idx = lines.FindIndex(l => l.Trim() == YoursMarker);
            if (idx < 0) return "";
            var body = lines.Skip(idx + 1).SkipWhile(l => l.Trim() == YoursNote).ToList();
            while (body.Count > 0 && body[body.Count - 1].Trim().Length == 0) body.RemoveAt(body.Count - 1);
            return body.Count == 0 ? "" : string.Join(Environment.NewLine, body) + Environment.NewLine;
        }

        public static void Write(string path, IEnumerable<ScriptEntry> entries)
        {
            var existing = File.Exists(path) ? File.ReadAllText(path) : "";
            File.WriteAllText(path, Build(entries, existing), new UTF8Encoding(false));
        }
    }
}
